#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"; cd "$ROOT"
: "${PGDATABASE:=postgres}"
# PM/SE verification evidence is generated by the Python pipeline before SQL load.
test -f results/verification_results.csv || { echo 'Run ./scripts/run_python_pipeline.sh first.'; exit 3; }
psql -v ON_ERROR_STOP=1 -d "$PGDATABASE" -f database/sql/01_schema.sql
psql -v ON_ERROR_STOP=1 -d "$PGDATABASE" -f database/sql/02_load_generated_data.sql
psql -v ON_ERROR_STOP=1 -d "$PGDATABASE" -f database/sql/03_views_kpi.sql
psql -v ON_ERROR_STOP=1 -d "$PGDATABASE" -f database/sql/05_load_pm_se_reference_data.sql
psql -v ON_ERROR_STOP=1 -d "$PGDATABASE" -f database/sql/04_validation_queries.sql | tee results/postgres_validation.txt
psql -v ON_ERROR_STOP=1 -d "$PGDATABASE" -f database/sql/06_e2e_crosscheck.sql
python scripts/compare_sql_python.py
