#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"; cd "$ROOT"
python -m pip install -q -r requirements.txt
# Remove stale derived evidence. Raw generated evidence will also be regenerated by the generator.
rm -f data/generated/python_kpi_crosscheck.csv \
      results/verification_results.csv results/benefit_realization.csv \
      results/e2e_crosscheck_report.csv results/sql_kpi_crosscheck.csv \
      results/sql_requirement_verification.csv results/sql_project_evm.csv
rm -f data/generated/telemetry_raw.csv
python analytics/python/generate_data.py
python analytics/python/validate_generated_data.py
python analytics/python/calculate_python_kpis.py
python -m pytest -q
python analytics/python/evaluate_requirements.py
python analytics/python/calculate_benefits.py
python analytics/python/monte_carlo_schedule.py | tee results/monte_carlo_schedule.txt
python analytics/python/generate_portfolio_charts.py
python scripts/generate_validation_manifest.py
